### ISSUE TITLE
Ragdoll death animation

### ISSUE THREAD

**Issue by MaxReimann** [philippotto/GP2013#107]
Todo:
- [x] import and use bullet ragdoll example
- [x] refactor example code
- [x] create simple view representation with cylinders as bones
- [ ] create unified bone system for view and model
- [ ] seperate and rework player 3dmodel in blender
- [ ] create skinning system and assign vertex groups to playermodel bones
- [ ] smooth bone weight for vertex groups 
- [ ] lock ragdoll on bike and release on death
