### ISSUE TITLE
unleash the drift power

### ISSUE THREAD

**Issue by philippotto** [philippotto/GP2013#47]
- [x] implement drifting with bike
- [ ] squeaking tires

if you drift close around an object
- [ ] give the user some gratification
- [ ] play whistling wind sound
